package models

import (
	"time"

	"gorm.io/datatypes"
)

type NodeRole string

const (
	NodeRoleHub    NodeRole = "hub"
	NodeRoleWorker NodeRole = "worker"
)

type NodeStatus string

const (
	NodeStatusActive         NodeStatus = "active"
	NodeStatusMaintenance    NodeStatus = "maintenance"
	NodeStatusOffline        NodeStatus = "offline"
	NodeStatusDecommissioned NodeStatus = "decommissioned"
)

type Node struct {
	ID        uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	// Gluon cluster membership
	ClusterID uint    `json:"cluster_id" gorm:"not null;index"`
	Cluster   Cluster `json:"cluster,omitempty" gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`

	// Identity
	Hostname string   `json:"hostname" gorm:"not null"`
	Role     NodeRole `json:"role" gorm:"not null"`

	// Network identity
	PublicIP string `json:"public_ip" gorm:"not null"`
	Provider string `json:"provider" gorm:"not null"`
	OS       string `json:"os" gorm:"not null"`

	// WireGuard configuration (embedded - each node has ONE interface)
	WGPublicKey  string `json:"wg_public_key" gorm:"not null;unique"`
	WGAddress    string `json:"wg_address" gorm:"not null;unique"` // Assigned by master (e.g., "10.0.0.5/24")
	WGListenPort int    `json:"wg_listen_port" gorm:"not null"`
	MTU          *int   `json:"mtu,omitempty"` // Optional MTU override (defaults to WireGuardProfile)
	// Note: Private key is generated by agent locally and never stored on master

	// Metadata (future use - not for Kubernetes, but for Gluon node organization)
	Labels datatypes.JSON `json:"labels,omitempty"` // Custom labels for filtering/organization
	Taints datatypes.JSON `json:"taints,omitempty"` // Custom taints (future use)

	// Status tracking
	Status     NodeStatus `json:"status" gorm:"default:'active';not null"`
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`

	// Relationships
	EnrolledByID        *uint `json:"enrolled_by_id,omitempty"`
	EnrolledBy          *User `json:"enrolled_by,omitempty" gorm:"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`
	EnrollmentRequestID uint  `json:"enrollment_request_id" gorm:"not null"`
}

type NodeEnrollmentRequest struct {
	// metadata
	ID          uint      `gorm:"primaryKey;autoIncrement" json:"id"`
	RequestedAt time.Time `json:"requested_at" gorm:"autoCreateTime"`
	Status      string    `json:"status" gorm:"default:'pending'"`

	// Gluon cluster the node wants to join
	ClusterID uint    `json:"cluster_id" gorm:"not null;index"`
	Cluster   Cluster `json:"cluster,omitempty" gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`

	// data from the agent
	Hostname    string   `json:"hostname" gorm:"not null"`
	PublicIP    string   `json:"public_ip" gorm:"not null"`
	Provider    string   `json:"provider" gorm:"not null"`
	OS          string   `json:"os" gorm:"not null"`
	DesiredRole NodeRole `json:"desired_role" gorm:"not null"`

	// Network info
	WGPublicKey  string `json:"wg_public_key" gorm:"not null"`
	WGListenPort int    `json:"wg_listen_port" gorm:"not null"`

	// decision - approved
	ApprovedAt   *time.Time `json:"approved_at,omitempty"`
	ApprovedByID *uint      `json:"approved_by_id,omitempty"`
	ApprovedBy   *User      `json:"approved_by,omitempty" gorm:"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`

	// decision - rejected
	RejectionReason string     `json:"rejection_reason,omitempty" gorm:"default:null"`
	RejectedAt      *time.Time `json:"rejected_at,omitempty"`
	RejectedByID    *uint      `json:"rejected_by_id,omitempty"`
	RejectedBy      *User      `json:"rejected_by,omitempty" gorm:"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`

	// if approved, the ID of the created Node
	ConvertedNodeID *uint `json:"converted_node_id,omitempty"`
}
